name: amit63
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dio: ^5.4.1
  intl: ^0.19.0
  jt_preferences: ^4.0.7

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
